<?php
return [
    'show' => [
        'Abdullahpur',
        'Agargaon',
        'Ashulia',
        'Badda',
        'Banani',
        'Banasree',
        'Baridhara',
        'Bashundhara',
        'Bawnia',
        'Beraid',
        'Birulia',
        'Cantonment area',
        'Dakshinkhan',
        'Dania',
        'Demra',
        'Dhanmondi',
        'Farmgate',
        'Gabtali',
        'Gazipur',
        'Gulshan',
        'Hazaribagh',
        'Islampur',
        'Jurain',
        'Kafrul',
        'Kakrail',
        'Kamalapur',
        'Kamrangirchar',
        'Kazipara',
        'Keraniganj',
        'Khilgaon',
        'Khilkhet',
        'Kotwali',
        'Lalbagh',
        'Matuail',
        'Mirpur',
        'Mohakhali',
        'Mohammadpur',
        'Motijheel',
        'Narayanganj',
        'Nimtoli',
        'Pallabi',
        'Paltan',
        'Ramna',
        'Rampura',
        'Sabujbagh',
        'Sadarghat',
        'Satarkul',
        'Savar',
        'Shahbagh',
        'Sher-e-Bangla Nagar',
        'Shyampur',
        'Sutrapur',
        'Tejgaon',
        'Tongi',
        'Uttara',
        'Uttarkhan',
        'Vatara',
        'Wari',
        'Out of Dhaka'

    ],
];
